name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main  # mainブランチへのpushをトリガー
  pull_request:
    branches:
      - main  # mainブランチへのPRをトリガー

jobs:
  build:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    steps:
      # 1. コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. PHPのセットアップ
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # 使用するPHPのバージョン（必要に応じて変更）

      # 3. Composerで依存関係のインストール
      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist

  deploy:
            needs: build
            runs-on: ubuntu-latest
        
            steps:
              - name: Checkout code
                uses: actions/checkout@v2
        
              - name: Install Heroku CLI
                run: curl https://cli-assets.heroku.com/install.sh | sudo bash
        
              - name: Authenticate Heroku CLI
                env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: |
                  echo "machine git.heroku.com login YukiYamamotty0713 password $HEROKU_API_KEY" > ~/.netrc
                  chmod 600 ~/.netrc
                  heroku auth:token
        
              - name: Set Heroku git remote
                env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: |
                  heroku git:remote -a pacific-castle-41954
        
              - name: Configure Git authentication
                run: git config --global credential.helper cache
        
              - name: Deploy to Heroku
                run: git push heroku main