name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main  # mainブランチへのpushをトリガー
  pull_request:
    branches:
      - main  # mainブランチへのPRをトリガー

jobs:
  build:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    steps:
      # 1. コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. PHPのセットアップ
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # 使用するPHPのバージョン（必要に応じて変更）

      # 3. Composerで依存関係のインストール
      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sudo bash

      - name: Verify Heroku CLI
        run: heroku --version

      - name: Heroku Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo $HEROKU_API_KEY | heroku auth:token

      - name: Check Heroku app exists
        run: heroku apps:info -a pacific-castle-41954
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Set Git config
        run: |
          git config --global user.email "yuuki330110713@gmail.com"
          git config --global user.name "YukiYamamotty0713"

      - name: Add Heroku remote
        run: heroku git:remote -a pacific-castle-41954
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: git push heroku main